// =========================================================
// FILE: src/components/admin/AdminNavIcon.tsx
// Иконки навигации админки. Фиксированный слот 18×18,
// чтобы знак стоял в одной линии с текстом — и у вкладки,
// и у группы.
// =========================================================

"use client";

import {
  Archive,
  BadgeCheck,
  BadgeDollarSign,
  BadgePercent,
  Banknote,
  Barcode,
  Bell,
  Bot,
  Box,
  Boxes,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  CalendarDays,
  Camera,
  ChartBar,
  ChartLine,
  ChartPie,
  CheckCircle2,
  CircleAlert,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Coins,
  Contact,
  CreditCard,
  Database,
  DoorOpen,
  Droplet,
  Eye,
  Factory,
  FileBarChart,
  FileSpreadsheet,
  FileText,
  Flame,
  FolderOpen,
  Gauge,
  Gift,
  Globe,
  Grid3x3,
  Group,
  HandCoins,
  Handshake,
  Headset,
  History,
  Hourglass,
  ImageIcon,
  Info,
  KeyRound,
  Landmark,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  List,
  ListChecks,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  NotebookPen,
  Package,
  PackageCheck,
  PackageOpen,
  PackagePlus,
  PackageSearch,
  Palette,
  PanelTop,
  Pencil,
  Phone,
  PiggyBank,
  Printer,
  QrCode,
  ReceiptText,
  Recycle,
  Rocket,
  Rows3,
  Ruler,
  Scale,
  ScanLine,
  Scissors,
  Search,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Star,
  Store,
  Table2,
  Tag,
  Tags,
  Target,
  TrendingDown,
  TrendingUp,
  Truck,
  User,
  UserCheck,
  UserPlus,
  UserSquare,
  UserStar,
  Users,
  Wallet,
  WalletCards,
  Warehouse,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  layout: Layout,
  "layout-grid": LayoutGrid,
  "layout-list": LayoutList,
  list: List,
  "rows-3": Rows3,
  "grid-3x3": Grid3x3,
  "panel-top": PanelTop,
  menu: Menu,
  sliders: SlidersHorizontal,
  "folder-open": FolderOpen,
  layers: Layers,
  archive: Archive,
  group: Group,
  briefcase: Briefcase,
  package: Package,
  box: Box,
  boxes: Boxes,
  "package-open": PackageOpen,
  "package-search": PackageSearch,
  "package-check": PackageCheck,
  "package-plus": PackagePlus,
  warehouse: Warehouse,
  factory: Factory,
  store: Store,
  "shopping-cart": ShoppingCart,
  tag: Tag,
  tags: Tags,
  barcode: Barcode,
  "qr-code": QrCode,
  "scan-line": ScanLine,
  ruler: Ruler,
  scissors: Scissors,
  truck: Truck,
  recycle: Recycle,
  droplet: Droplet,
  landmark: Landmark,
  wallet: Wallet,
  "wallet-cards": WalletCards,
  "credit-card": CreditCard,
  banknote: Banknote,
  coins: Coins,
  "hand-coins": HandCoins,
  "piggy-bank": PiggyBank,
  receipt: ReceiptText,
  "badge-dollar": BadgeDollarSign,
  "badge-percent": BadgePercent,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "chart-bar": ChartBar,
  "chart-line": ChartLine,
  "chart-pie": ChartPie,
  gauge: Gauge,
  target: Target,
  calculator: Calculator,
  scale: Scale,
  users: Users,
  user: User,
  "user-square": UserSquare,
  "user-check": UserCheck,
  "user-plus": UserPlus,
  "user-star": UserStar,
  contact: Contact,
  headset: Headset,
  handshake: Handshake,
  shield: Shield,
  "shield-check": ShieldCheck,
  "file-text": FileText,
  "file-spreadsheet": FileSpreadsheet,
  "file-bar-chart": FileBarChart,
  "table-2": Table2,
  "clipboard-list": ClipboardList,
  "clipboard-check": ClipboardCheck,
  "list-checks": ListChecks,
  printer: Printer,
  database: Database,
  notebook: NotebookPen,
  settings: Settings,
  "settings-2": Settings2,
  wrench: Wrench,
  key: KeyRound,
  lock: Lock,
  eye: Eye,
  search: Search,
  bell: Bell,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  clock: Clock,
  history: History,
  hourglass: Hourglass,
  star: Star,
  flame: Flame,
  zap: Zap,
  sparkles: Sparkles,
  gift: Gift,
  megaphone: Megaphone,
  rocket: Rocket,
  info: Info,
  "badge-check": BadgeCheck,
  "circle-alert": CircleAlert,
  "check-circle": CheckCircle2,
  "door-open": DoorOpen,
  "building-2": Building2,
  "map-pin": MapPin,
  globe: Globe,
  phone: Phone,
  mail: Mail,
  "message-circle": MessageCircle,
  bot: Bot,
  camera: Camera,
  image: ImageIcon,
  palette: Palette,
  pencil: Pencil,
};

export function AdminNavIcon({
  id,
  size = 18,
  className,
}: {
  id: string;
  size?: number;
  className?: string;
}) {
  const Icon = ICON_MAP[id] || FolderOpen;
  return (
    <Icon
      size={size}
      strokeWidth={1.75}
      absoluteStrokeWidth
      className={`admin-nav-ico${className ? ` ${className}` : ""}`}
      aria-hidden="true"
    />
  );
}
